name: Optimized Pipeline

on:
  workflow_dispatch:

jobs:
  calculator-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run calculator tests
        run: |
          PYTHONPATH=. pytest tests/test_calculator.py

  textprocessor-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run textprocessor tests
        run: |
          PYTHONPATH=. pytest tests/test_textprocessor.py
